name: Run Simulation and Create Release

on:
  push:
    branches:
      - main

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib

    - name: Run simulation
      id: run_simulation
      run: |
        output = $(python simulation.py --initial_loan 450000 --interest_rate 8.5 --minimum_amortization 2500 --investment_return 6 --years 15 --monthly_payment 6000)
        echo "::set-output name=output::$output"

    - name: Upload result.png
      uses: actions/upload-artifact@v4
      with:
        name: result-image
        path: result.png

    - name: Upload output.txt
      uses: actions/upload-artifact@v4
      with:
        name: simulation-output
        path: output.txt

    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      id: create_release
      with:
        body: |
          ```
          ${{ steps.run_simulation.outputs.output }}
          ```
          ![Result Image](https://github.com/skaramicke/mortgage-or-invest/releases/download/v1/result.png)
        name: Simulation Results
        tag: v1
        allowUpdates: true
        artifactContentType: image/png

    - name: Upload result.png to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: result.png
        asset_name: result.png
        asset_content_type: image/png

    - name: Upload output.txt to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: output.txt
        asset_name: output.txt
        asset_content_type: text/plain